language: node_js
node_js:
  - "0.10"
  - "0.11"

before_install:
  - npm install -g gulp

script:
  - gulp lint
  - gulp style
  - npm run cover

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls --verbose
